// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBh8RH6bfPsfbhjUoYxYM1xwLuhBZMrfI',
    appId: '1:395749114288:web:b030ab33e107581ed81675',
    messagingSenderId: '395749114288',
    projectId: 'cleanup-96db1',
    authDomain: 'cleanup-96db1.firebaseapp.com',
    storageBucket: 'cleanup-96db1.appspot.com',
    measurementId: 'G-JM1V3XGENF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYG9z_ONvVTwbhipEIr7EBY1cie_f4IaE',
    appId: '1:395749114288:android:067e9b79b34eb2f6d81675',
    messagingSenderId: '395749114288',
    projectId: 'cleanup-96db1',
    storageBucket: 'cleanup-96db1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmyJLe3lyXL6COJFnNsXg1ee8qfIJm4i0',
    appId: '1:395749114288:ios:e261e965338cf793d81675',
    messagingSenderId: '395749114288',
    projectId: 'cleanup-96db1',
    storageBucket: 'cleanup-96db1.appspot.com',
    iosClientId: '395749114288-v9b9lo68acnug7cdlphb079ugq9tccae.apps.googleusercontent.com',
    iosBundleId: 'com.example.tunisiacleanup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmyJLe3lyXL6COJFnNsXg1ee8qfIJm4i0',
    appId: '1:395749114288:ios:72e16bff89dde255d81675',
    messagingSenderId: '395749114288',
    projectId: 'cleanup-96db1',
    storageBucket: 'cleanup-96db1.appspot.com',
    iosClientId: '395749114288-ms994skfbeq6bodd7hrij89m06ekjd30.apps.googleusercontent.com',
    iosBundleId: 'com.example.tunisiacleanup.RunnerTests',
  );
}
